# Generated by Django 2.1.3 on 2019-01-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20170820_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicaopagamento',
            options={'verbose_name': 'Condição de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='orcamentovenda',
            options={'verbose_name': 'Orçamento de Venda'},
        ),
        migrations.AlterModelOptions(
            name='pedidovenda',
            options={'permissions': (('faturar_pedidovenda', 'Pode faturar Pedidos de Venda'),), 'verbose_name': 'Pedido de Venda'},
        ),
        migrations.AlterField(
            model_name='venda',
            name='local_orig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='venda_local_estoque', to='estoque.LocalEstoque'),
        ),
    ]
