# Generated by Django 2.1.3 on 2019-01-06 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20170820_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto'},
        ),
        migrations.AlterModelOptions(
            name='transportadora',
            options={'verbose_name': 'Transportadora'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'verbose_name': 'Unidade'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.NaturezaOperacao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='grupo_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.GrupoFiscal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.Marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.Unidade'),
        ),
    ]
